# Populate LS_COLORS (this requires `dircolors`)
eval $(dircolors)

# Simplify navigation
setopt auto_cd

# ===============================
# Completion
# ===============================
# Display a selection menu for completion
zstyle ':completion:*' menu select
# Colorful selection menu
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# Case insensitive completion if there's no capitable letter
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
# A bunch of other fancy options from prezto
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:corrections' format ' %F{green}-- %d (errors: %e) --%f'
zstyle ':completion:*:descriptions' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
zstyle ':completion:*' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes

# ===============================
# History
# ===============================
# Share history file amongst all Zsh sessions, ignoring dupes
setopt append_history share_history histignorealldups
# Ctrl+R runs fzf-history-widget. That comes from the fzf zsh integration
# enabled in default.nix.

# direnv integration but this is now done by home-manager:
# https://github.com/nix-community/home-manager/blob/release-24.05/modules/programs/direnv.nix#L121
# eval "$(direnv hook zsh)"

# On MAC keyboard, Super and Alt are swapped which is very confusing.  This
# function swaps them back. See: https://unix.stackexchange.com/a/226641/45689
function fix_apple_keyboard() {
    echo "swapping Alt and Super"
    echo 1 | sudo tee /sys/module/hid_apple/parameters/swap_opt_cmd

    echo "disabling fn keys"
    echo 2 | sudo tee /sys/module/hid_apple/parameters/fnmode
}

